import {chromium} from 'playwright-core';
const browser=await chromium.launch({executablePath:'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',headless:true});
const errors=[];
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())});
page.on('pageerror',error=>errors.push(error.message));
await page.goto('http://127.0.0.1:5174',{waitUntil:'networkidle'});
await page.screenshot({path:'welcome-redesign.png',fullPage:true});
await page.getByRole('button',{name:/meet Maya/i}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'setup-redesign.png',fullPage:true});
await page.getByRole('button',{name:/negative/i}).click();
await page.getByRole('button',{name:/begin the lesson/i}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'lesson-redesign.png',fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
mobile.on('pageerror',error=>errors.push(`mobile: ${error.message}`));
await mobile.goto('http://127.0.0.1:5174',{waitUntil:'networkidle'});
await mobile.screenshot({path:'welcome-mobile.png',fullPage:true});
console.log(JSON.stringify({title:await page.title(),stage:await page.locator('main').getAttribute('class'),desktopOverflow:await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),mobileOverflow:await mobile.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth),errors},null,2));
await browser.close();
if(errors.length)process.exit(1);
