import {useEffect,useRef,useState} from 'react';
import {ArrowRight,Mic,MoreHorizontal,Send,Volume2} from 'lucide-react';
import {motion} from 'framer-motion';
import {Brand} from './Brand';import {MentalModel} from './MentalModel';import {useStore} from '../store';
export function Teaching(){
  const {topic,persona,messages,beliefs,teach,setStage,turn,busy,mode,error}=useStore();
  const [text,setText]=useState('');const [elapsed,setElapsed]=useState(0);const [listening,setListening]=useState(false);const end=useRef<HTMLDivElement>(null);
  useEffect(()=>{const x=setInterval(()=>setElapsed(v=>v+1),1000);return()=>clearInterval(x)},[]);useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy]);
  const send=()=>{if(!text.trim()||busy)return;void teach(text.trim());setText('')};
  const speak=()=>{const R=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!R){setListening(true);setTimeout(()=>{setListening(false);setText('The mechanism is that ')},900);return}const r=new R();r.onresult=(e:any)=>setText(e.results[0][0].transcript);r.onend=()=>setListening(false);setListening(true);r.start()};
  return <main className="teaching paper"><header className="lesson-header"><Brand/><div className="lesson-meta"><span>{topic?.subject}</span><b>{topic?.title}</b><small>{topic?.level}</small></div><div className={`mode-badge ${mode}`}>{mode==='live'?'LIVE MODEL':'OFFLINE DEMO'}</div><div className="timer"><span className="live-dot"/>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</div><button className="quiet" aria-label="Lesson options"><MoreHorizontal/></button></header>{error?<div className="model-error">{error} Responses are currently using the clearly labeled offline fallback.</div>:null}<div className="lesson-body"><section className="transcript"><header><div><span className="kicker">YOUR LESSON</span><h2>Teach it plainly.</h2></div><span className="persona">Maya · {persona}</span></header><div className="messages">{messages.map(m=><motion.article initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={m.role} key={m.id}><div className="who">{m.role==='teacher'?'YOU':'M'}</div><div><small>{m.role==='teacher'?'You':'Maya'} · {m.time}</small><p>{m.text}</p>{m.role==='student'?<button className="listen" onClick={()=>window.speechSynthesis?.speak(new SpeechSynthesisUtterance(m.text))}><Volume2 size={13}/> listen</button>:null}</div></motion.article>)}{busy?<article className="student thinking"><div className="who">M</div><div><small>MAYA IS THINKING</small><p><i/><i/><i/></p></div></article>:null}<div ref={end}/></div><div className="composer"><textarea aria-label="Your explanation" value={text} disabled={busy} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Explain the next piece in your own words..."/><div><button className={`mic ${listening?'active':''}`} onClick={speak}><Mic size={17}/>{listening?'Listening…':'Speak'}</button><span>↵ to send</span><button className="send" disabled={busy} onClick={send} aria-label="Send explanation"><Send size={17}/></button></div></div></section><MentalModel/></div><footer className="lesson-footer"><div><span>{turn}</span> teaching turns <i/> <b>{beliefs.filter(b=>b.status==='solid').length}</b> beliefs secured</div><button disabled={busy} className="test-btn" onClick={()=>setStage('exam')}>I’m done — test her <ArrowRight size={17}/></button></footer></main>
}
