import {useCallback,useEffect,useRef,useState} from 'react';
import {Check,Mic,RotateCcw,X} from 'lucide-react';
import {motion,AnimatePresence} from 'framer-motion';
import {usePreferences} from '../lib/preferences';

type ResultEvent={results:ArrayLike<{isFinal:boolean;0:{transcript:string}}>};
type RecognitionInstance={continuous:boolean;interimResults:boolean;lang:string;onresult:((event:ResultEvent)=>void)|null;onerror:((event:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;stop:()=>void;abort:()=>void};
type RecognitionConstructor=new()=>RecognitionInstance;
function getRecognition(){const source=window as unknown as {SpeechRecognition?:RecognitionConstructor;webkitSpeechRecognition?:RecognitionConstructor};return source.SpeechRecognition??source.webkitSpeechRecognition}
const format=(seconds:number)=>`${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`;

export function VoiceCapture({open,onClose,onUse}:{open:boolean;onClose:()=>void;onUse:(text:string,send:boolean)=>void}){const language=usePreferences(state=>state.recognitionLanguage);const autoSend=usePreferences(state=>state.autoSendVoice);const [status,setStatus]=useState<'ready'|'listening'|'review'|'error'>('ready');const [transcript,setTranscript]=useState('');const [interim,setInterim]=useState('');const [seconds,setSeconds]=useState(0);const [error,setError]=useState('');const recognition=useRef<RecognitionInstance|null>(null);const finalText=useRef('');const interimText=useRef('');
  const begin=useCallback(()=>{const Constructor=getRecognition();if(!Constructor){setStatus('error');setError('Live transcription is not supported in this browser. Try Chrome, Edge, or Safari.');return}setTranscript('');setInterim('');finalText.current='';interimText.current='';setSeconds(0);setError('');const instance=new Constructor();instance.continuous=true;instance.interimResults=true;instance.lang=language;instance.onresult=event=>{let live='';let completed='';for(let i=0;i<event.results.length;i++){const phrase=event.results[i][0]?.transcript??'';if(event.results[i].isFinal)completed=`${completed} ${phrase}`.trim();else live=`${live} ${phrase}`.trim()}finalText.current=completed;interimText.current=live;setTranscript(completed);setInterim(live)};instance.onerror=event=>{if(event.error==='aborted')return;setError(event.error==='not-allowed'?'Microphone access was blocked. Allow it in your browser’s address bar, then try again.':`The microphone stopped (${event.error}). Please try once more.`);setStatus('error')};instance.onend=()=>setStatus(current=>current==='listening'?(finalText.current||interimText.current?'review':'ready'):current);recognition.current=instance;setStatus('listening');try{instance.start()}catch{setStatus('error');setError('The microphone could not start. Check that another app is not using it.')}},[language]);
  const stop=()=>{const combined=`${transcript} ${interim}`.trim();finalText.current=combined;setTranscript(combined);setInterim('');setStatus(combined?'review':'ready');recognition.current?.stop()};const close=()=>{recognition.current?.abort();recognition.current=null;onClose()};const use=()=>{const result=`${transcript} ${interim}`.trim();if(result){onUse(result,autoSend);close()}};
  useEffect(()=>{if(!open)return;setStatus('ready');setTranscript('');setInterim('');setError('');const delay=window.setTimeout(begin,350);return()=>{window.clearTimeout(delay);recognition.current?.abort();recognition.current=null}},[open,begin]);useEffect(()=>{if(status!=='listening')return;const timer=window.setInterval(()=>setSeconds(value=>value+1),1000);return()=>window.clearInterval(timer)},[status]);
  return <AnimatePresence>{open?<motion.section className={`voice-float ${status}`} initial={{opacity:0,scale:.96,y:4}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.97,y:3}} role="region" aria-live="polite" aria-label="Voice explanation"><button className={`water-drop ${status}`} onClick={status==='listening'?stop:undefined} aria-label={status==='listening'?'Stop recording':'Voice recording status'}><i/><i/><Mic/></button><div className="voice-whisper"><span>{status==='listening'?`LISTENING · ${format(seconds)}`:status==='review'?'EXPLANATION READY':status==='error'?'MICROPHONE PAUSED':'CONNECTING…'}</span><p>{error||(transcript||interim)||'Speak naturally — I’m listening.'}</p></div><div className="voice-actions">{status==='listening'?<><button onClick={close} aria-label="Cancel recording"><X/></button><button onClick={stop}>DONE</button></>:status==='review'?<><button onClick={begin} aria-label="Record again"><RotateCcw/></button><button className="voice-use" onClick={use}><Check/> {autoSend?'SEND':'USE'}</button></>:status==='error'?<><button onClick={close}><X/></button><button onClick={begin}><RotateCcw/> RETRY</button></>:<button onClick={close}><X/></button>}</div></motion.section>:null}</AnimatePresence>}
