import {create} from 'zustand';
import {runBlindExam,teachStudent} from './lib/ai';
import {saveLesson} from './lib/persistence';
import type {Belief,ExamResult,LessonSnapshot,Message,Stage,Topic} from './types';
type Mode='live'|'error';type Persistence='idle'|'saving'|'saved'|'error';
type State={stage:Stage;lessonId:string|null;topic:Topic|null;persona:string;messages:Message[];beliefs:Belief[];turn:number;busy:boolean;mode:Mode;error:string|null;exam:ExamResult|null;persistence:Persistence;savedAt:string|null;setStage:(s:Stage)=>void;start:(t:Topic,p:string)=>Promise<void>;teach:(text:string)=>Promise<void>;runExam:()=>Promise<boolean>;resume:(lesson:LessonSnapshot)=>void;reset:()=>void};
const positions=[[16,18],[55,12],[35,62],[68,55]];const now=()=>new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const messageOf=(error:unknown)=>error instanceof Error?error.message:'The request failed unexpectedly.';
function snapshot(state:State,stage?:Stage):LessonSnapshot|null{if(!state.lessonId||!state.topic)return null;const target=stage??state.stage;if(target==='welcome'||target==='setup')return null;return {id:state.lessonId,topic:state.topic,persona:state.persona,stage:target,messages:state.messages,beliefs:state.beliefs,exam:state.exam,turn:state.turn}}
export const useStore=create<State>((set,get)=>{
  const persist=async(stage?:Stage)=>{const lesson=snapshot(get(),stage);if(!lesson)return;set({persistence:'saving'});try{await saveLesson(lesson);set({persistence:'saved',savedAt:new Date().toISOString()})}catch(error){set({persistence:'error',error:`Your lesson could not be archived: ${messageOf(error)}`})}};
  return {stage:'welcome',lessonId:null,topic:null,persona:'Curious child',messages:[],beliefs:[],turn:0,busy:false,mode:'live',error:null,exam:null,persistence:'idle',savedAt:null,
    setStage:(stage)=>{set({stage});void persist(stage)},
    start:async(topic,persona)=>{const id=crypto.randomUUID();const initial:Message={id:'m0',role:'student',text:`Hi—I’m Maya. I think I sort of know ${topic.title.toLowerCase()}, but every explanation loses me. Will you teach it to me?`,time:now()};set({lessonId:id,topic,persona,turn:0,busy:true,mode:'live',error:null,exam:null,persistence:'saving',messages:[initial],beliefs:topic.misconceptions.map((claim,index)=>({id:`b${index}`,claim,confidence:.9-index*.12,status:'misconception',x:positions[index][0],y:positions[index][1]}))});try{const lesson=snapshot({...get(),stage:'teach'} as State,'teach');if(lesson)await saveLesson(lesson);set({stage:'teach',busy:false,persistence:'saved',savedAt:new Date().toISOString()})}catch(error){set({busy:false,persistence:'error',error:`The lesson could not be opened: ${messageOf(error)}`})}},
    teach:async(text)=>{const state=get();if(!state.topic||!state.lessonId||state.busy)return;const teacher:Message={id:`t${Date.now()}`,role:'teacher',text,time:now()};const messages=[...state.messages,teacher];set({messages,busy:true,error:null,mode:'live'});try{const result=await teachStudent(state.lessonId,state.topic,state.persona,messages,state.beliefs);const old=new Map(state.beliefs.map(belief=>[belief.id,{x:belief.x,y:belief.y}]));const beliefs=result.beliefs.map((belief,index)=>({...belief,...(old.get(belief.id)??{x:positions[index%positions.length][0],y:positions[index%positions.length][1]})}));set({messages:[...messages,{id:`s${Date.now()}`,role:'student',text:result.reply,time:now()}],beliefs,turn:state.turn+1,busy:false,mode:'live'});await persist()}catch(error){set({busy:false,mode:'error',error:messageOf(error)})}},
    runExam:async()=>{const state=get();if(!state.topic||!state.lessonId)return false;set({busy:true,error:null,mode:'live'});try{const exam=await runBlindExam(state.lessonId,state.topic,state.messages,state.beliefs);set({exam,busy:false,mode:'live'});await persist('results');return true}catch(error){set({busy:false,mode:'error',error:messageOf(error),stage:'teach'});await persist('teach');return false}},
    resume:(lesson)=>set({stage:lesson.stage,lessonId:lesson.id,topic:lesson.topic,persona:lesson.persona,messages:lesson.messages,beliefs:lesson.beliefs,exam:lesson.exam,turn:lesson.turn,busy:false,mode:'live',error:null,persistence:'saved',savedAt:lesson.updatedAt??null}),
    reset:()=>set({stage:'welcome',lessonId:null,topic:null,messages:[],beliefs:[],turn:0,busy:false,mode:'live',error:null,exam:null,persistence:'idle',savedAt:null})
  }
});
