import {z} from 'zod';
import {createClerkClient} from '@clerk/backend';
import {requireAuth} from '../server/auth.js';
import {getSql} from '../server/db.js';
import {enforceRateLimit,RateLimitError} from '../server/guardrails.js';
import {logComplete,reportError,requestContext} from '../server/observability.js';

const profile=z.object({firstName:z.string().trim().min(1).max(50)});
const clerk=()=>createClerkClient({secretKey:process.env.CLERK_SECRET_KEY});
export default async function handler(request,response){const context=requestContext(request,'/api/account');const session=await requireAuth(request,response);if(!session)return;try{await enforceRateLimit(response,{identity:session.sub,key:`account:${request.method}`,limit:10,windowSeconds:60});const sql=getSql();
  if(request.method==='GET'&&request.query?.action==='export'){const [lessons,topics,generations]=await Promise.all([sql`SELECT id,topic,persona,stage,messages,beliefs,exam,turn,status,created_at,updated_at,completed_at FROM lessons WHERE user_id=${session.sub} ORDER BY created_at`,sql`SELECT normalized_title,request,topic,model,token_usage,status,created_at,updated_at FROM generated_topics WHERE user_id=${session.sub} ORDER BY created_at`,sql`SELECT lesson_id,kind,model,token_usage,duration_ms,status,created_at,completed_at FROM ai_generations WHERE user_id=${session.sub} ORDER BY created_at`]);const payload={product:'Protégé',exportedAt:new Date().toISOString(),accountId:session.sub,lessons,generatedTopics:topics,aiGenerationLedger:generations};response.setHeader('content-type','application/json; charset=utf-8');response.setHeader('content-disposition',`attachment; filename="protege-export-${new Date().toISOString().slice(0,10)}.json"`);logComplete(context,200,{kind:'export'});return response.status(200).send(JSON.stringify(payload,null,2))}
  if(request.method==='PATCH'){const body=profile.parse(request.body);const user=await clerk().users.updateUser(session.sub,{firstName:body.firstName});logComplete(context,200);return response.status(200).json({firstName:user.firstName||body.firstName,email:user.primaryEmailAddress?.emailAddress||''})}
  if(request.method==='DELETE'){if(request.body?.confirmation!=='DELETE MY ACCOUNT')return response.status(400).json({error:'Type DELETE MY ACCOUNT to confirm.'});await sql`DELETE FROM lessons WHERE user_id=${session.sub}`;await sql`DELETE FROM generated_topics WHERE user_id=${session.sub}`;await sql`DELETE FROM error_events WHERE user_id=${session.sub}`;await sql`DELETE FROM rate_limit_windows WHERE identity=${session.sub}`;await sql`DELETE FROM generation_leases WHERE identity=${session.sub}`;await clerk().users.deleteUser(session.sub);logComplete(context,200,{kind:'account_deleted'});return response.status(200).json({deleted:true})}
  return response.status(405).json({error:'Method not allowed'});
}catch(error){const status=error instanceof z.ZodError?400:error instanceof RateLimitError?429:500;const incidentId=status===500?await reportError(error,context,{userId:session.sub,status,kind:'account'}):undefined;logComplete(context,status);return response.status(status).json({error:error instanceof z.ZodError?'Please enter a valid display name.':error instanceof RateLimitError?error.message:'Your account request could not be completed.',incidentId})}}
