import {requireAuth} from '../server/auth.js';
import {getSql} from '../server/db.js';
import {enforceRateLimit,RateLimitError} from '../server/guardrails.js';
import {logComplete,reportError,requestContext} from '../server/observability.js';

const average=values=>values.length?Math.round(values.reduce((sum,value)=>sum+value,0)/values.length):0;
export default async function handler(request,response){
  const context=requestContext(request,'/api/dashboard');if(request.method!=='GET')return response.status(405).json({error:'Method not allowed'});const session=await requireAuth(request,response);if(!session)return;
  try{
    await enforceRateLimit(response,{identity:session.sub,key:'dashboard',limit:30,windowSeconds:60});const sql=getSql();
    const [lessons,modelRows,errorRows]=await Promise.all([
      sql`SELECT id,topic,stage,messages,beliefs,exam,turn,status,created_at,updated_at FROM lessons WHERE user_id=${session.sub} ORDER BY updated_at DESC LIMIT 100`,
      sql`SELECT COUNT(*)::int total,COUNT(*) FILTER (WHERE status='complete')::int successful,COALESCE(ROUND(AVG(duration_ms) FILTER (WHERE status='complete')),0)::int avg_latency_ms,COUNT(*) FILTER (WHERE routing->>'failover'='true')::int failovers FROM ai_generations WHERE user_id=${session.sub} AND created_at>NOW()-INTERVAL '30 days'`,
      sql`SELECT COUNT(*)::int total FROM error_events WHERE user_id=${session.sub} AND created_at>NOW()-INTERVAL '30 days'`
    ]);
    const completed=lessons.filter(lesson=>lesson.status==='complete'&&lesson.exam);const scores=completed.map(lesson=>Number(lesson.exam.total)||0);const beliefs=lessons.flatMap(lesson=>Array.isArray(lesson.beliefs)?lesson.beliefs:[]);const cleared=beliefs.filter(belief=>belief.status==='solid').length;
    const subjectMap=new Map();for(const lesson of lessons){const subject=lesson.topic?.subject||'Other';const item=subjectMap.get(subject)||{subject,sessions:0,scores:[],cleared:0,beliefs:0};item.sessions++;if(lesson.exam)item.scores.push(Number(lesson.exam.total)||0);for(const belief of lesson.beliefs||[]){item.beliefs++;if(belief.status==='solid')item.cleared++}subjectMap.set(subject,item)}
    const subjects=[...subjectMap.values()].map(item=>({subject:item.subject,sessions:item.sessions,averageScore:average(item.scores),mastery:item.beliefs?Math.round(item.cleared/item.beliefs*100):0})).sort((a,b)=>b.sessions-a.sessions);
    const gapMap=new Map();for(const lesson of completed)for(const gap of lesson.exam?.gaps||[]){const type=gap.type||'unknown';const item=gapMap.get(type)||{type,count:0,cost:0,example:gap.fix};item.count++;item.cost+=Number(gap.cost)||0;gapMap.set(type,item)}
    const misconceptionMap=new Map();for(const lesson of lessons)for(const belief of lesson.beliefs||[]){const existing=misconceptionMap.get(belief.claim)||{claim:belief.claim,subject:lesson.topic?.subject||'Other',encounters:0,cleared:0,confidence:0,replacement:belief.replacement};existing.encounters++;if(belief.status==='solid')existing.cleared++;existing.confidence+=Number(belief.confidence)||0;if(belief.replacement)existing.replacement=belief.replacement;misconceptionMap.set(belief.claim,existing)}
    const misconceptions=[...misconceptionMap.values()].map(item=>({...item,confidence:Math.round(item.confidence/item.encounters*100)})).sort((a,b)=>(b.encounters-b.cleared)-(a.encounters-a.cleared)).slice(0,8);
    const activeDays=[...new Set(lessons.map(lesson=>new Date(lesson.updated_at).toISOString().slice(0,10)))].sort().reverse();let streak=0;let cursor=new Date();cursor.setHours(0,0,0,0);for(const day of activeDays){const date=new Date(`${day}T00:00:00`);const diff=Math.round((cursor-date)/86400000);if(diff===0||diff===1){streak++;cursor=date}else break}
    const trend=completed.slice(0,10).reverse().map(lesson=>({id:lesson.id,title:lesson.topic.title,subject:lesson.topic.subject,score:Number(lesson.exam.total)||0,date:lesson.updated_at}));const weakest=subjects.filter(item=>item.sessions>0).sort((a,b)=>(a.averageScore||101)-(b.averageScore||101))[0];const pending=lessons.find(lesson=>lesson.status!=='complete');
    const recent=lessons.slice(0,8).map(lesson=>({id:lesson.id,title:lesson.topic.title,subject:lesson.topic.subject,level:lesson.topic.level,stage:lesson.stage,status:lesson.status,score:lesson.exam?.total??null,turn:lesson.turn,updatedAt:lesson.updated_at}));const model=modelRows[0];
    const payload={overview:{sessions:lessons.length,completed:completed.length,averageScore:average(scores),explanations:lessons.reduce((sum,lesson)=>sum+(Number(lesson.turn)||0),0),mastery:beliefs.length?Math.round(cleared/beliefs.length*100):0,cleared,totalBeliefs:beliefs.length,streak},subjects,trend,misconceptions,coaching:[...gapMap.values()].sort((a,b)=>b.cost-a.cost).slice(0,5),recent,next:{kind:pending?'resume':weakest?'strengthen':'start',lessonId:pending?.id||null,title:pending?.topic?.title||weakest?.subject||'Your first lesson',reason:pending?'You left this mental model unfinished.':weakest?`${weakest.subject} is your highest-leverage teaching frontier.`:'Build your first measurable mental model.'},system:{successRate:model.total?Math.round(model.successful/model.total*100):100,avgLatencyMs:Number(model.avg_latency_ms)||0,failovers:Number(model.failovers)||0,incidents:Number(errorRows[0].total)||0}};
    logComplete(context,200,{lessons:lessons.length});return response.status(200).json(payload);
  }catch(error){const status=error instanceof RateLimitError?429:500;const incidentId=status===500?await reportError(error,context,{userId:session.sub,status,kind:'dashboard'}):undefined;logComplete(context,status);return response.status(status).json({error:error instanceof RateLimitError?error.message:'Your Learning Map is temporarily unavailable.',incidentId,retryAfter:error instanceof RateLimitError?error.retryAfter:undefined})}
}
